services:
  - type: web
    name: bewcloud
    env: docker
    plan: starter
    healthCheckPath: /
    envVars:
      - key: BASE_URL
        fromService:
          name: bewcloud
          type: web
          property: host
      - key: POSTGRESQL_HOST
        fromDatabase:
          name: bewcloud
          property: host
      - key: POSTGRESQL_USER
        fromDatabase:
          name: bewcloud
          property: user
      - key: POSTGRESQL_PASSWORD
        fromDatabase:
          name: bewcloud
          property: password
      - key: POSTGRESQL_DBNAME
        fromDatabase:
          name: bewcloud
          property: database
      - key: POSTGRESQL_PORT
        fromDatabase:
          name: bewcloud
          property: port

databases:
  - name: bewcloud
    plan: starter
